### ISSUE TITLE
Fix Flow errors

### ISSUE THREAD

**Issue by satya164** [react-native-paper/react-native-paper#50]

**Comment by sreejithr** [comment]
Made a pull request [here](https://github.com/react-native-paper/react-native-paper/pull/52). I've bumped the version of flow in our project so that it matches with react-native's flow version (0.33). It fixes this error:

```
node_modules/react-native/Libraries/EventEmitter/EmitterSubscription.js:0
EmitterSubscription. Duplicate module provider
current provider. See: example/node_modules/fbemitter/lib/EmitterSubscription.js:0

node_modules/react-native/Libraries/EventEmitter/EventSubscription.js:0
EventSubscription. Duplicate module provider
current provider. See: example/node_modules/fbemitter/lib/EventSubscription.js:0

node_modules/react-native/Libraries/EventEmitter/EventSubscriptionVendor.js:0
EventSubscriptionVendor. Duplicate module provider
current provider. See: example/node_modules/fbemitter/lib/EventSubscriptionVendor.js:0
```

I'm new to flow. So, I haven't yet figured out why it is not picking up libraries `ex-navigation` and `react-native-vector-icons` from `example/node_modules`.

I ignored @exponent/ex-navigation in .flowconfig since the library had tons of flow errors. Didn't make sense to have those errors in our flow results.

Otherwise, the changes I've made are obvious enough I believe. Do let me know if everything is in order. Thank you.

**Comment by satya164** [comment]
I've copied your comment there so I'll just reply there.
